Edit controllers
DurkaTechnologies/AdminPanel pull request #10
Opened 2021-08-17 23:41 UTC by deathCodeDevelop

2021-08-17 23:49 UTC, ColdForeign commented on WebUI/Areas/Admin/Views/Role/_ViewAll.cshtml
> +                             }
Unnecessary parenthesis

2021-08-17 23:50 UTC, ColdForeign commented on WebUI/Areas/Admin/Views/User/_Create.cshtml
>  </script>
No newline at end of file

2021-08-17 23:54 UTC, deathCodeDevelop commented on WebUI/Areas/Admin/Views/User/_Create.cshtml
>  </script>
</script>
```

2021-08-18 00:02 UTC, ColdForeign requested changes

2021-08-18 00:03 UTC, deathCodeDevelop commented on WebUI/Areas/Entities/Controllers/CommunityController.cs
> +
```      
```

2021-08-18 00:04 UTC, deathCodeDevelop commented on WebUI/Areas/Entities/Views/Worker/_ViewAll.cshtml
> +    });</script>
```suggestion
    });
    </script>
```

2021-08-18 00:07 UTC, ColdForeign approved these changes

2021-08-18 00:08 UTC, merged

2021-08-18 00:15 UTC, ColdForeign reviewed
good